### ISSUE TITLE
NullReference when clearing collection DataGrid is bound to while item is selected

### ISSUE THREAD

**Issue by Xiard** [MyToolkit/MyToolkit#15]
Here is the collection my DataGrid is bound to:

        private ObservableCollection<VoiceoverWorkOrderListItemViewModel> _voiceoverWorkOrders;

        public ObservableCollection<VoiceoverWorkOrderListItemViewModel> VoiceoverWorkOrders {
            get { return _voiceoverWorkOrders; }
        }

        private void DisposeVoiceoverWorkOrders() {
            if (VoiceoverWorkOrders == null) return;
            foreach (var woli in VoiceoverWorkOrders) {
                woli.Model.PropertyChanged -= WorkOrderPropertyChanged;
                woli.Dispose();
            }
             // exception occurs at this line
            VoiceoverWorkOrders.Clear();
        } 

I am getting an exception on Clear:

System.NullReferenceException occurred
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MyToolkit.Extended
  StackTrace:
       at MyToolkit.Controls.DataGridRow.UpdateRowBackgroundBrush()
       at MyToolkit.Controls.DataGridRow.set_IsSelected(Boolean value)
       at MyToolkit.Controls.DataGrid.ChangeItemSelection(Object item, Boolean isSelected)
       at MyToolkit.Controls.DataGrid.OnSelectionChanged(Object sender, SelectionChangedEventArgs e)
       at MyToolkit.Collections.ObservableCollectionViewBase`1.OnInternalCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
       at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
       at MyToolkit.Collections.MtObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
       at MyToolkit.Collections.MtObservableCollection`1.Initialize(IEnumerable`1 collection)
       at MyToolkit.Collections.ObservableCollectionViewBase`1.Refresh()
       at MyToolkit.Collections.ObservableCollectionViewBase`1.OnOriginalCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
       at MyToolkit.Collections.ObservableCollectionViewBase`1.<TrackCollection>b__11(ObservableCollectionViewBase`1 subscriber, Object s, NotifyCollectionChangedEventArgs e)
       at MyToolkit.Events.WeakEvent.<>c__DisplayClass6`3.<RegisterEvent>b__5(Object s, TArgs e)
       at MyToolkit.Collections.ObservableCollectionViewBase`1.<>c__DisplayClass16.<TrackCollection>b__10(Object o, NotifyCollectionChangedEventArgs e)
       at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
       at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
       at System.Collections.ObjectModel.Collection`1.Clear()
       at SightAndSay.ViewModels.PurchasesViewModel.DisposeVoiceoverWorkOrders()
  InnerException:

**Comment by rsuter** [comment]
I could not reproduce the problem in the SampleUwpApp, but I added an extra null check in UpdateRowBackgroundBrush. Please clone the latest source code and add project references to MyToolkit.csproj and MyToolkit.Extended.Uwp.csproj to test the latest changes in your application... Is the problem solved?

**Comment by Xiard** [comment]
It does appear to fix the issue.  I also put a breakpoint on UpdateRowBackgroundBrush, and at this point in the code listBoxItem is null:

![image](https://cloud.githubusercontent.com/assets/12835753/10269432/991d8928-6aa5-11e5-9177-c44cfac6a322.png)

**Comment by Xiard** [comment]
FWIW, note that the page that contains the DataGrid is being unloaded as I navigate to a different part of the app.  So I'm not simply disposing of the collection, and this may be happening in conjunction with the DataGrid being unloaded.

**Comment by rsuter** [comment]
Yes, this is probably the reason...
