### ISSUE TITLE
Exception at MtPage.RegisterViewModel

### ISSUE THREAD

**Issue by asd4059** [MyToolkit/MyToolkit#21]
ViewModelHelper.RegisterViewModelForStateHandling:
page.PageStateHandler is null

Exception
   at MyToolkit.Mvvm.ViewModelHelper.RegisterViewModelForStateHandling(IStateHandlingViewModel viewModel, MtPage page)
   at MyToolkit.Mvvm.ViewModelHelper.RegisterViewModel(ViewModelBase viewModel, FrameworkElement view, Boolean registerForStateHandling)
   at MyToolkit.Paging.MtPage.RegisterViewModel(ViewModelBase viewModel, Boolean registerForStateHandling)
   at MusicPlayer.UI.MainPage..ctor()

**Comment by rsuter** [comment]
Thanks for reporting, will fix tomorrow...

**Comment by rsuter** [comment]
Should be fixed in v2.5.2, please verify if it works now

**Comment by asd4059** [comment]
Now works correctly, thanks.
