### ISSUE TITLE
bind to CollectionViewSource?

### ISSUE THREAD

**Issue by ddelapasse2** [MyToolkit/MyToolkit#58]
Hi, We've been using the binding pattern described here https://msdn.microsoft.com/en-us/windows.ui.xaml.data.binding.source  (search down for "teamcvs").  Basically, you define a CollectionViewSource in the xaml as a resource and then you can bind ListView/GridView controls to that resource.  This doesn't seem to work in MyToolkit.

<CollectionViewSource x:Name="GroupedMusicListSource" Source="{x:Bind MainModel.GroupedMusicList}"     IsSourceGrouped="True"  ItemsPath="Items" />
...
 ItemsSource="{x:Bind MainModel.UngroupedMusicList}"

This doesn't seem to work on the MyToolkit grid.  Is there any way to accomplish this?  The idea is that the data is arranged in a grouped list with a <string key, IEnumerable<object> items> and this let's you attach the "items" themselves directly to the control.

**Comment by rsuter** [comment]
Are there any errors in the output? Are there any special changes needed to support `x:Bind`?

**Comment by ddelapasse2** [comment]
^Sorry, some of my post was gobbled up by github.  There IS an exception:

System.ArgumentNullException: Value cannot be null.
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at MyToolkit.Utilities.ReflectionExtensions.CreateGenericObject(Type type, Type innerType, Object[] args)
   at MyToolkit.Controls.DataGrid.UpdateItemsSource()
   at MyToolkit.Controls.DataGrid.Initialize()
   at MyToolkit.Controls.DataGrid.OnApplyTemplate()

The CollectionViewSource is defined like this:
CollectionViewSource x:Name="UngroupedMusicListSource"  Source="{x:Bind MainModel.UngroupedMusicList}"  IsSourceGrouped="False"

and I can set my grid's ItemsSource="{x:Bind MainModel.UngroupedMusicList}"
but not ItemsSource="{Binding Source={StaticResource UngroupedMusicListSource}}"

In this example the 2 should be equivalent, but there's power to this technique when you have a grouped source collection (and in that case IsSourceGrouped would be true).

**Comment by rsuter** [comment]
This seems like a problem with .NET Native and reflection: The DataGrid tries to create a generic ObservableCollectionView instance of the bound item type. As a workaround, create an ObservableCollectionView with your items and bind this... Ill see if there is a fix for that...

**Comment by rsuter** [comment]
Grouped items is currently not supported by the DataGrid

**Comment by govindrawat55** [comment]
Is virtualization possible in this Datagrid ?

**Comment by rsuter** [comment]
I think virtualization is supported, yes
